#! /usr/bin/env python
import logging
from argparse import ArgumentParser

import uwsgifouinelib as main


def init_logger():
    logger = logging.getLogger('uwsgiFouine')
    logger.setLevel(logging.ERROR)
    h = logging.StreamHandler()
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    h.setFormatter(formatter)
    logger.addHandler(h)
    return logger

logger = init_logger()


parser = ArgumentParser()
parser.add_argument('logfile', nargs='?', default=None)
parser.add_argument('--debug', action='store_true',
                    help='Debug mode (overrides silent mode)'),
main.add_parse_arguments(parser)
args = parser.parse_args()

if args.debug:
    logger.setLevel(logging.DEBUG)

main.parse_log(args.logfile, args)
