#!/usr/bin/env python


# adjust the path so we can find the lib directory files
import sys
import os
sys.path.append(os.path.dirname(__file__) + '/lib')


import logging
from optparse import OptionParser
import main


def init_logger():
    logger = logging.getLogger('uwsgiFouine')
    logger.setLevel(logging.WARN)
    h = logging.StreamHandler()
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    h.setFormatter(formatter)
    logger.addHandler(h)
    return logger

logger = init_logger()


parser = OptionParser(usage="usage: %prog [options] input_file")
parser.add_option('--debug', action='store_true',
                  dest='debugmode', default=False,
                  help='Debug mode (overrides silent mode)'),
main.add_parse_options(parser)
(options, args) = parser.parse_args()

if not len(args) == 1:
    parser.print_help()
    sys.exit()

if options.debugmode:
    logger.setLevel(logging.DEBUG)

import cProfile
cProfile.run('main.parse_log(args[0], options)', 'foo')
s = pstats.Stats('foo')
s.sort_stats('cumulative').print_stats(10)
#######################################################
import sys; sys.stdout = sys.stderr
from IPython import embed; embed()
import sys; sys.exit()
#######################################################
